name: publish-latest
on: 
    push:
        branches:
            - ci-test
jobs:
    compile-pdf:
        name: Compile pdf
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository 
              uses: actions/checkout@v2
              with:
                path: '${{ github.workspace }}/taoe3'
            
            - name: Display some filesystem data
              run: |
                pwd
                ls -lah
                echo ${{ github.workspace }}
                find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
                ls -lah ${{ github.workspace }}/taoe3


            - name: Compile pdf
              uses: xu-cheng/latex-action@v2
              with:
                    root_file: ${{ github.workspace }}/taoe3/main.tex
                    work_in_root_file_dir: True

            - name: Checkout gh_pages branch
              uses: actions/checkout@v2
              with:
                path: '${{ github.workspace }}/gh_pages'
                ssh-key: "${{ secrets.COMMIT_KEY }}"
                ref: 'gh_pages'

            - name: Upload to GH Pages
              run: |
                pwd
                ls -lah
                cd ${{ github.workspace }}
                find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
                pwd
                ls -lah
                mv ${{ github.workspace }}/taoe3/main.pdf ${{ github.workspace }}/gh_pages/data/taoe3-solutions.pdf
                cd ${{ github.workspace }}/gh_pages
                pwd
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                git add data/taoe3-solutions.pdf
                git commit -m "Updating solutions with copy from $GITHUB_SHA"
                git push origin gh_pages
