name: publish-latest
on: 
    push:
        branches:
            - master
jobs:
    compile-pdf:
        name: Compile pdf
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository 
              uses: actions/checkout@v2
              with:
                path: './taoe3'

            - name: Compile pdf
              uses: xu-cheng/latex-action@v2
              with:
                    working_directory: './taoe3'
                    root_file: main.tex

            - name: Checkout gh_pages branch
              uses: actions/checkout@v2
              with:
                path: './gh_pages'
                ssh-key: "${{ secrets.COMMIT_KEY }}"

            - name: Upload to GH Pages
              run: |
                mv taoe3/main.pdf gh_pages/data/taoe3-solutions.pdf
                cd gh_pages
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                git add data/taoe3-solutions.pdf
                git commit -m "Updating solutions with copy from $GITHUB_SHA"
                git push origin gh_pages
